### ISSUE TITLE
Helm repo not working - 404

### ISSUE THREAD

**Issue by Naterd** [ntppool/charts#2]
```https://charts.ntppool.org/ smtp` failed exit status 1: Error: looks like "https://charts.ntppool.org/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.ntppool.org/index.yaml : 404 Not Found```

When attempting to run

`helm repo add ntppool https://charts.ntppool.org/`

This appears to have broken within the last day or so.

**Comment by abh** [comment]
Doh, thank you. I moved the setup so it should work again now!
