### ISSUE TITLE
Error: UPGRADE FAILED: template: smtp/templates/config.yaml:12:26: executing "smtp/templates/config.yaml" at <b64enc>: wrong type for value; expected string; got int64

### ISSUE THREAD

**Issue by prolixalias** [ntppool/charts#3]
Hello there! Helm v3.12.1...

When using the SMARTHOST_* settings, adding port generates the title text. If I remove it, it defaults to 25 - which is not good in our case. Oddly enough, I can b64 the number/string and it passes but mail doesn't relay due to the b64 string being appended as port in running config.

```shell
helm upgrade --install smtp smtp \
  --repo https://charts.ntppool.org/  \
  --version 2.1.1 \
  --namespace relay --create-namespace \
  --set config.SMARTHOST_ADDRESS="some.smarthost" \
  --set config.SMARTHOST_PORT=587 \
  --set config.SMARTHOST_USER="some.username" \
  --set config.SMARTHOST_PASSWORD="some.password" \
  --set config.SMARTHOST_ALIASES="some.alias \
  --set config.RELAY_NETWORKS=':192.168.0.0/16'
```

I'd submit a PR but can't make heads nor tails of what's going on here.

**Comment by abh** [comment]
Thanks @prolixalias -- I think I fixed it in v2.1.2 that's getting published now.

0374e933261
